"""Password, one-time-code and API-key hashing.

Argon2id is the algorithm: ``argon2-cffi`` is a hard dependency of ``apps/api`` and is
installed, so this is the path every deployment and every test takes. PBKDF2-HMAC-SHA256
from the standard library remains as a fallback for a host that cannot build the C
extension (ADR-005 describes the build host that could not). Both encodings are
self-describing and ``verify_password`` reads either, so a deployment that moves between
the two re-hashes on the next successful login rather than invalidating every password.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import secrets

#: Every way ``PasswordHasher.verify`` can reject the stored string. Held as a tuple
#: because the fallback branch cannot rebind the imported name — assigning ``Exception``
#: over a class is an error the type checker rejects — and because the two failures do not
#: share a base: ``VerifyMismatchError`` is an ``Argon2Error`` (the password is wrong)
#: while ``InvalidHashError`` is a ``ValueError`` (the stored string is not an argon2 hash
#: at all). Both mean "this password does not verify", never a 500, so both are caught.
#: A bare ``except Exception`` here would say the same thing and also swallow the
#: programming mistakes this module should surface.
_VERIFY_ERRORS: tuple[type[BaseException], ...]

try:
    from argon2 import PasswordHasher
    from argon2.exceptions import InvalidHashError, VerificationError

    _ARGON2: PasswordHasher | None = PasswordHasher()
    _VERIFY_ERRORS = (VerificationError, InvalidHashError)
except ImportError:  # pragma: no cover - only a host without the C extension
    _ARGON2 = None
    _VERIFY_ERRORS = (ValueError,)

#: OWASP's 2023 floor for PBKDF2-HMAC-SHA256. Raise it, never lower it.
PBKDF2_ROUNDS = 600_000
_PBKDF2_PREFIX = "pbkdf2_sha256"


def argon2_available() -> bool:
    """True when the preferred hasher is installed. Tests assert the fallback works too."""
    return _ARGON2 is not None


def _pbkdf2_hash(password: str, salt: bytes, rounds: int) -> str:
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, rounds)
    return "$".join(
        (
            _PBKDF2_PREFIX,
            str(rounds),
            base64.b64encode(salt).decode("ascii"),
            base64.b64encode(digest).decode("ascii"),
        )
    )


def hash_password(password: str) -> str:
    """Hash a staff password with the strongest algorithm this process has."""
    if _ARGON2 is not None:
        return str(_ARGON2.hash(password))
    return _pbkdf2_hash(password, secrets.token_bytes(16), PBKDF2_ROUNDS)


def verify_password(password: str, encoded: str | None) -> bool:
    """Constant-time check that accepts either encoding.

    A missing hash (a vendor account, which authenticates by one-time code) is a failure,
    not an error: the password endpoint must not become a way to tell accounts apart.
    """
    if not encoded:
        return False
    if encoded.startswith(f"{_PBKDF2_PREFIX}$"):
        try:
            _, rounds_text, salt_b64, _digest_b64 = encoded.split("$", 3)
            rounds = int(rounds_text)
            salt = base64.b64decode(salt_b64)
        except (ValueError, TypeError):
            return False
        candidate = _pbkdf2_hash(password, salt, rounds)
        return hmac.compare_digest(candidate, encoded)
    if _ARGON2 is not None:
        try:
            return bool(_ARGON2.verify(encoded, password))
        except _VERIFY_ERRORS:
            return False
    return False


def hash_token(token: str) -> str:
    """Hash a high-entropy secret — a one-time code or an API key.

    These are not passwords: they are generated by the server with full entropy and are
    checked on every machine request, so a slow KDF buys nothing and costs latency. SHA-256
    over the raw token is the right trade, exactly as for a session identifier.
    """
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def tokens_match(token: str, hashed: str) -> bool:
    return hmac.compare_digest(hash_token(token), hashed)
