"""Password, one-time-code and API-key hashing.

Argon2id is the intended algorithm (``argon2-cffi`` is in ``pyproject.toml``). It is a
C extension and it is not installable on the build host (ADR-005: PyPI is blocked), so the
module degrades to PBKDF2-HMAC-SHA256 from the standard library. Both encodings are
self-describing and ``verify_password`` reads either, which means a deployment that gains
argon2 re-hashes on the next successful login rather than invalidating every password.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import secrets

try:  # pragma: no cover - exercised only where argon2-cffi is installed
    from argon2 import PasswordHasher
    from argon2.exceptions import VerifyMismatchError

    _ARGON2: PasswordHasher | None = PasswordHasher()
except ImportError:  # pragma: no cover - the build host's path
    _ARGON2 = None
    VerifyMismatchError = Exception

#: OWASP's 2023 floor for PBKDF2-HMAC-SHA256. Raise it, never lower it.
PBKDF2_ROUNDS = 600_000
_PBKDF2_PREFIX = "pbkdf2_sha256"


def argon2_available() -> bool:
    """True when the preferred hasher is installed. Tests assert the fallback works too."""
    return _ARGON2 is not None


def _pbkdf2_hash(password: str, salt: bytes, rounds: int) -> str:
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, rounds)
    return "$".join(
        (
            _PBKDF2_PREFIX,
            str(rounds),
            base64.b64encode(salt).decode("ascii"),
            base64.b64encode(digest).decode("ascii"),
        )
    )


def hash_password(password: str) -> str:
    """Hash a staff password with the strongest algorithm this process has."""
    if _ARGON2 is not None:  # pragma: no cover - not reachable on the build host
        return str(_ARGON2.hash(password))
    return _pbkdf2_hash(password, secrets.token_bytes(16), PBKDF2_ROUNDS)


def verify_password(password: str, encoded: str | None) -> bool:
    """Constant-time check that accepts either encoding.

    A missing hash (a vendor account, which authenticates by one-time code) is a failure,
    not an error: the password endpoint must not become a way to tell accounts apart.
    """
    if not encoded:
        return False
    if encoded.startswith(f"{_PBKDF2_PREFIX}$"):
        try:
            _, rounds_text, salt_b64, _digest_b64 = encoded.split("$", 3)
            rounds = int(rounds_text)
            salt = base64.b64decode(salt_b64)
        except (ValueError, TypeError):
            return False
        candidate = _pbkdf2_hash(password, salt, rounds)
        return hmac.compare_digest(candidate, encoded)
    if _ARGON2 is not None:  # pragma: no cover - not reachable on the build host
        try:
            return bool(_ARGON2.verify(encoded, password))
        except (VerifyMismatchError, Exception):
            return False
    return False


def hash_token(token: str) -> str:
    """Hash a high-entropy secret — a one-time code or an API key.

    These are not passwords: they are generated by the server with full entropy and are
    checked on every machine request, so a slow KDF buys nothing and costs latency. SHA-256
    over the raw token is the right trade, exactly as for a session identifier.
    """
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def tokens_match(token: str, hashed: str) -> bool:
    return hmac.compare_digest(hash_token(token), hashed)
