"""init

Revision ID: 0001
Revises:
Create Date: 2026-08-26 09:42:25.352432+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Native PostgreSQL enum types created implicitly by ``op.create_table``. Alembic does
#: not drop them on downgrade, so ``downgrade()`` removes them explicitly — otherwise a
#: downgrade/upgrade round-trip fails with "type ... already exists".
ENUM_TYPES = (
    "application_status",
    "category_kind",
    "cycle_kind",
    "cycle_status",
    "decision_kind",
    "document_status",
    "observation_source",
    "project_stage",
    "score_class",
    "sync_result",
    "user_role",
    "vendor_status",
    "vendor_type",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name_az", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.Enum("work", "material", name="category_kind"), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["category.id"],
            name=op.f("fk_category_parent_id_category"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
        sa.UniqueConstraint("code", name=op.f("uq_category_code")),
    )
    op.create_index(op.f("ix_category_kind"), "category", ["kind"], unique=False)
    op.create_table(
        "event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event")),
    )
    op.create_index(op.f("ix_event_created_at"), "event", ["created_at"], unique=False)
    op.create_index("ix_event_entity", "event", ["entity_type", "entity_id"], unique=False)
    op.create_index(op.f("ix_event_type"), "event", ["type"], unique=False)
    op.create_table(
        "otp_code",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("code_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_code")),
    )
    op.create_index(op.f("ix_otp_code_email"), "otp_code", ["email"], unique=False)
    op.create_table(
        "project",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("client", sa.String(length=255), nullable=True),
        sa.Column(
            "stage",
            sa.Enum("pipeline", "go_nogo", "tender", "execution", name="project_stage"),
            nullable=False,
        ),
        sa.Column("estimated_value", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("external_ref", sa.String(length=128), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
        sa.UniqueConstraint("code", name=op.f("uq_project_code")),
    )
    op.create_index(op.f("ix_project_external_ref"), "project", ["external_ref"], unique=False)
    op.create_index(op.f("ix_project_is_demo"), "project", ["is_demo"], unique=False)
    op.create_table(
        "scoring_model",
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("vendor_type", sa.Enum("sub", "sup", "both", name="vendor_type"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("classes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pass_mark", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("validity_months", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_scoring_model")),
    )
    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_setting")),
    )
    op.create_table(
        "vendor",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("voen", sa.String(length=10), nullable=True),
        sa.Column("type", sa.Enum("sub", "sup", "both", name="vendor_type"), nullable=False),
        sa.Column("legal_form", sa.String(length=64), nullable=True),
        sa.Column("registration_year", sa.Integer(), nullable=True),
        sa.Column("address", sa.String(length=512), nullable=True),
        sa.Column("region", sa.String(length=128), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "registered",
                "invited",
                "in_progress",
                "submitted",
                "under_review",
                "information_requested",
                "prequalified",
                "rejected",
                "suspended",
                name="vendor_status",
            ),
            nullable=False,
        ),
        sa.Column("external_ref", sa.String(length=128), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("voen ~ '^[0-9]{10}$'", name=op.f("ck_vendor_voen_ten_digits")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor")),
        sa.UniqueConstraint("voen", name=op.f("uq_vendor_voen")),
    )
    op.create_index(op.f("ix_vendor_external_ref"), "vendor", ["external_ref"], unique=False)
    op.create_index(op.f("ix_vendor_is_demo"), "vendor", ["is_demo"], unique=False)
    op.create_index(
        "ix_vendor_legal_name_lower", "vendor", [sa.text("lower(legal_name)")], unique=False
    )
    op.create_index(op.f("ix_vendor_status"), "vendor", ["status"], unique=False)
    op.create_index("ix_vendor_status_type", "vendor", ["status", "type"], unique=False)
    op.create_table(
        "webhook",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("secret", sa.String(length=255), nullable=False),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook")),
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("vendor", "officer", "commission", "manager", "admin", name="user_role"),
            nullable=False,
        ),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("totp_secret", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_app_user_vendor_id_vendor"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
    )
    op.create_index(op.f("ix_app_user_role"), "app_user", ["role"], unique=False)
    op.create_index(op.f("ix_app_user_vendor_id"), "app_user", ["vendor_id"], unique=False)
    op.create_table(
        "contact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.String(length=128), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_contact_vendor_id_vendor"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
    )
    op.create_index(op.f("ix_contact_email"), "contact", ["email"], unique=False)
    op.create_index(op.f("ix_contact_vendor_id"), "contact", ["vendor_id"], unique=False)
    op.create_table(
        "performance_record",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("on_time_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("quality_ncr_count", sa.Integer(), nullable=True),
        sa.Column("hse_incidents", sa.Integer(), nullable=True),
        sa.Column("payment_disputes", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("recorded_by_name", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_performance_record_project_id_project"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_performance_record_vendor_id_vendor"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_performance_record")),
    )
    op.create_index(
        op.f("ix_performance_record_project_id"), "performance_record", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_performance_record_vendor_id"), "performance_record", ["vendor_id"], unique=False
    )
    op.create_table(
        "qualification_cycle",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.Enum("tender", "periodic", name="cycle_kind"), nullable=False),
        sa.Column("scoring_model_version", sa.String(length=32), nullable=False),
        sa.Column("opens_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closes_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "open", "closed", "archived", name="cycle_status"),
            nullable=False,
        ),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_qualification_cycle_project_id_project"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["scoring_model_version"],
            ["scoring_model.version"],
            name=op.f("fk_qualification_cycle_scoring_model_version_scoring_model"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qualification_cycle")),
    )
    op.create_table(
        "sync_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("adapter", sa.String(length=64), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fields_written", sa.Integer(), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "result", sa.Enum("success", "partial", "failed", name="sync_result"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_sync_log_vendor_id_vendor"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_log")),
    )
    op.create_index(op.f("ix_sync_log_adapter"), "sync_log", ["adapter"], unique=False)
    op.create_index(op.f("ix_sync_log_vendor_id"), "sync_log", ["vendor_id"], unique=False)
    op.create_table(
        "vendor_category",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_vendor_category_category_id_category"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_vendor_category_vendor_id_vendor"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_category")),
        sa.UniqueConstraint(
            "vendor_id", "category_id", name=op.f("uq_vendor_category_vendor_id_category_id")
        ),
    )
    op.create_index(
        op.f("ix_vendor_category_category_id"), "vendor_category", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_vendor_category_vendor_id"), "vendor_category", ["vendor_id"], unique=False
    )
    op.create_table(
        "work_package",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("estimated_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "min_class", sa.Enum("A", "B", "C", "D", "F", "KO", name="score_class"), nullable=False
        ),
        sa.Column("required_certs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_work_package_category_id_category"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_work_package_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_package")),
    )
    op.create_index(
        op.f("ix_work_package_category_id"), "work_package", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_package_project_id"), "work_package", ["project_id"], unique=False
    )
    op.create_table(
        "api_key",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("hashed_key", sa.String(length=255), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_api_key_created_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_key")),
        sa.UniqueConstraint("hashed_key", name=op.f("uq_api_key_hashed_key")),
    )
    op.create_table(
        "application",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("cycle_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "invited",
                "in_progress",
                "submitted",
                "under_review",
                "information_requested",
                "prequalified",
                "rejected",
                "withdrawn",
                name="application_status",
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("declaration", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rubric_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("computed", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "decision",
            sa.Enum("approve", "reject", "request_info", name="decision_kind"),
            nullable=True,
        ),
        sa.Column("justification", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("second_rubric", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cycle_id"],
            ["qualification_cycle.id"],
            name=op.f("fk_application_cycle_id_qualification_cycle"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["app_user.id"],
            name=op.f("fk_application_decided_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_application_vendor_id_vendor"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application")),
        sa.UniqueConstraint(
            "vendor_id", "cycle_id", name=op.f("uq_application_vendor_id_cycle_id")
        ),
    )
    op.create_index(op.f("ix_application_cycle_id"), "application", ["cycle_id"], unique=False)
    op.create_index(op.f("ix_application_status"), "application", ["status"], unique=False)
    op.create_index(op.f("ix_application_vendor_id"), "application", ["vendor_id"], unique=False)
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["app_user.id"],
            name=op.f("fk_audit_event_actor_id_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    op.create_index(op.f("ix_audit_event_actor_id"), "audit_event", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_event_created_at"), "audit_event", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_event_entity", "audit_event", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("file_key", sa.String(length=512), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded", "in_preparation", "not_applicable", "missing", name="document_status"
            ),
            nullable=False,
        ),
        sa.Column("verified_by", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_document_vendor_id_vendor"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by"],
            ["app_user.id"],
            name=op.f("fk_document_verified_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document")),
    )
    op.create_index(op.f("ix_document_code"), "document", ["code"], unique=False)
    op.create_index("ix_document_expiry", "document", ["expiry_date"], unique=False)
    op.create_index(op.f("ix_document_vendor_id"), "document", ["vendor_id"], unique=False)
    op.create_table(
        "field_observation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=False),
        sa.Column("field_code", sa.String(length=32), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "registry",
                "api",
                "document",
                "portal",
                "excel",
                "manual",
                name="observation_source",
            ),
            nullable=False,
        ),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("entered_by", sa.Uuid(), nullable=True),
        sa.Column(
            "trust_rank",
            sa.SmallInteger(),
            sa.Computed(
                "CASE source WHEN 'registry'::observation_source THEN 1 WHEN 'api'::observation_source THEN 2 WHEN 'document'::observation_source THEN 3 WHEN 'portal'::observation_source THEN 4 WHEN 'excel'::observation_source THEN 4 WHEN 'manual'::observation_source THEN 5 ELSE 9 END",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entered_by"],
            ["app_user.id"],
            name=op.f("fk_field_observation_entered_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_field_observation_vendor_id_vendor"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_observation")),
    )
    op.create_index(
        "ix_field_observation_current",
        "field_observation",
        ["vendor_id", "field_code", "trust_rank", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_observation_vendor_id"), "field_observation", ["vendor_id"], unique=False
    )
    op.create_table(
        "match_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "ran_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ran_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
            name=op.f("fk_match_run_project_id_project"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ran_by"],
            ["app_user.id"],
            name=op.f("fk_match_run_ran_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_run")),
    )
    op.create_index(op.f("ix_match_run_project_id"), "match_run", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_run_project_id"), table_name="match_run")
    op.drop_table("match_run")
    op.drop_index(op.f("ix_field_observation_vendor_id"), table_name="field_observation")
    op.drop_index("ix_field_observation_current", table_name="field_observation")
    op.drop_table("field_observation")
    op.drop_index(op.f("ix_document_vendor_id"), table_name="document")
    op.drop_index("ix_document_expiry", table_name="document")
    op.drop_index(op.f("ix_document_code"), table_name="document")
    op.drop_table("document")
    op.drop_index("ix_audit_event_entity", table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_created_at"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_actor_id"), table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_index(op.f("ix_application_vendor_id"), table_name="application")
    op.drop_index(op.f("ix_application_status"), table_name="application")
    op.drop_index(op.f("ix_application_cycle_id"), table_name="application")
    op.drop_table("application")
    op.drop_table("api_key")
    op.drop_index(op.f("ix_work_package_project_id"), table_name="work_package")
    op.drop_index(op.f("ix_work_package_category_id"), table_name="work_package")
    op.drop_table("work_package")
    op.drop_index(op.f("ix_vendor_category_vendor_id"), table_name="vendor_category")
    op.drop_index(op.f("ix_vendor_category_category_id"), table_name="vendor_category")
    op.drop_table("vendor_category")
    op.drop_index(op.f("ix_sync_log_vendor_id"), table_name="sync_log")
    op.drop_index(op.f("ix_sync_log_adapter"), table_name="sync_log")
    op.drop_table("sync_log")
    op.drop_table("qualification_cycle")
    op.drop_index(op.f("ix_performance_record_vendor_id"), table_name="performance_record")
    op.drop_index(op.f("ix_performance_record_project_id"), table_name="performance_record")
    op.drop_table("performance_record")
    op.drop_index(op.f("ix_contact_vendor_id"), table_name="contact")
    op.drop_index(op.f("ix_contact_email"), table_name="contact")
    op.drop_table("contact")
    op.drop_index(op.f("ix_app_user_vendor_id"), table_name="app_user")
    op.drop_index(op.f("ix_app_user_role"), table_name="app_user")
    op.drop_table("app_user")
    op.drop_table("webhook")
    op.drop_index("ix_vendor_status_type", table_name="vendor")
    op.drop_index(op.f("ix_vendor_status"), table_name="vendor")
    op.drop_index("ix_vendor_legal_name_lower", table_name="vendor")
    op.drop_index(op.f("ix_vendor_is_demo"), table_name="vendor")
    op.drop_index(op.f("ix_vendor_external_ref"), table_name="vendor")
    op.drop_table("vendor")
    op.drop_table("setting")
    op.drop_table("scoring_model")
    op.drop_index(op.f("ix_project_is_demo"), table_name="project")
    op.drop_index(op.f("ix_project_external_ref"), table_name="project")
    op.drop_table("project")
    op.drop_index(op.f("ix_otp_code_email"), table_name="otp_code")
    op.drop_table("otp_code")
    op.drop_index(op.f("ix_event_type"), table_name="event")
    op.drop_index("ix_event_entity", table_name="event")
    op.drop_index(op.f("ix_event_created_at"), table_name="event")
    op.drop_table("event")
    op.drop_index(op.f("ix_category_kind"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
    for enum_name in ENUM_TYPES:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))
