"""adapter config, import previews and the api key prefix

Three change requests from the phase-2E integration worker, which correctly filed them
instead of writing a migration itself.

* `adapter_config` — per-vendor connector settings had been stored as `setting` rows.
  `services/settings_store.py` refuses keys outside its five declared groups, so that
  configuration was invisible to the admin settings screen and uneditable through it, while
  still deciding whether a scheduled pull runs.
* `import_preview` — a parsed workbook awaiting the officer's confirmation lived in process
  memory. Correct for one process, silently wrong behind a load balancer: the confirmation
  can land on a different worker than the one that parsed the file.
* `api_key.prefix` — declared by the contract's `ApiKey` with no column behind it, so it
  could only ever be returned by `createApiKey` and never listed.

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-26
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adapter_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("adapter", sa.String(length=64), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("base_url", sa.String(length=1024), nullable=True),
        sa.Column("auth_type", sa.String(length=16), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("secret", sa.Text(), nullable=True),
        sa.Column("field_map", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schedule_cron", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_adapter_config_vendor_id_vendor"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_adapter_config")),
        sa.UniqueConstraint("adapter", "vendor_id", name="uq_adapter_config_target"),
    )
    op.create_index(op.f("ix_adapter_config_adapter"), "adapter_config", ["adapter"], unique=False)
    op.create_index(
        op.f("ix_adapter_config_vendor_id"), "adapter_config", ["vendor_id"], unique=False
    )
    op.create_table(
        "import_preview",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vendor_id", sa.Uuid(), nullable=True),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parsed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["app_user.id"],
            name=op.f("fk_import_preview_created_by_app_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.id"],
            name=op.f("fk_import_preview_vendor_id_vendor"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_preview")),
    )
    op.create_index(
        op.f("ix_import_preview_vendor_id"), "import_preview", ["vendor_id"], unique=False
    )
    op.add_column("api_key", sa.Column("prefix", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_key", "prefix")
    op.drop_index(op.f("ix_import_preview_vendor_id"), table_name="import_preview")
    op.drop_table("import_preview")
    op.drop_index(op.f("ix_adapter_config_vendor_id"), table_name="adapter_config")
    op.drop_index(op.f("ix_adapter_config_adapter"), table_name="adapter_config")
    op.drop_table("adapter_config")
    # ### end Alembic commands ###
